### ISSUE TITLE
Only partial string returned when it contains a colon

### ISSUE THREAD

**Issue by finwo** [tidwall/json.c#2]
Parsed json: `["Runtime: 5 seconds"]`

Expected behavior:

When fetching the first string from the array, the whole string is returned

Actual behavior:

When trying to fetch the string value from the array, only the section before the colon was removed (`Runtime`) instead of the whole string.

**Comment by tidwall** [comment]
I'm unable to reproduce this issue on my side.
Can you provide an example? 

Here's what I tried:

```C
#include <stdio.h>
#include "json.h"

int main() {
    struct json json = json_parse("[\"Runtime: 5 seconds\"]"); 
    json = json_first(json);
    printf("%.*s\n", (int)json_raw_length(json), json_raw(json));
    char str[512];
    json_string_copy(json, str, sizeof(str));
    printf("%s\n", str);
    return 0;
}
// Output:
// "Runtime: 5 seconds"
// Runtime: 5 seconds
```

**Comment by finwo** [comment]
By now I've changed out the code that was having the issues, I'll attempt to provide a self-contained example of the issue later today.

**Comment by finwo** [comment]
I've replicated how the issues shows in this repository: https://github.com/finwo/tidwall-jsonc-issue-2

Basically, what I'm suspecting at the moment, is the `-O2` flag breaking something with the wrong optimizations.

---

Just checked, with `-O1`, `-O0` and without an `-O` flag it shows the same behavior.

---

Here's a quick extract from the stdout, as produced by the `fn_set_title` function in `main.c`:

```
---[ New set title request ]---

Req: ["Runtime: 3 seconds"]
Seq: 3

"Runtime: 3 seconds"
Runtime
```

**Comment by tidwall** [comment]
You have a [bug](https://github.com/finwo/tidwall-jsonc-issue-2/blob/47b660855a27c6905abf3919aaa4788e5e914c85/src/main.c#L30) in your code.

```C
char *newTitle = calloc(512, 1);
json_string_copy(json, newTitle, sizeof(newTitle));
```

In your case, the return value of `json_string_copy` is 7, which is telling you that only 7 characters (`Runtime`) have been copied to `newTitle`. 

The reason for this is because `sizeof(newTitle)` is effectively the same as `sizeof(char*)` which is likely going to be 8 on a 64-bit computer. Thus, `json_string_copy(json, newTitle, sizeof(newTitle))` is only writing 8 total bytes to `newTitle` (first 7 characters + null-terminator).

The fix is to either use an array on the stack (instead of a heap allocation)

```C
char newTitle[512];
json_string_copy(json, newTitle, sizeof(newTitle));
```

or provide the `json_string_copy` the number of allocated bytes

```C
char *newTitle = calloc(512, 1);
json_string_copy(json, newTitle, 512);
```

**Comment by finwo** [comment]
Well, the colon just happened to line up then :sweat_smile: 

Fixed the example using https://github.com/finwo/tidwall-jsonc-issue-2/commit/2c7ded0f5fff9ac4de9ee77c1b5001ce5bda9211

Sorry for taking your time, and thank you for your help!

**Comment by tidwall** [comment]
No worries. I'm happy to help. :)
